[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Terminess Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font"
style = "Regular Italic"

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[keyboard]
